### ISSUE TITLE
[Bug]: Incorrect version of the Serial Number is used by the Dfci validation test

### ISSUE THREAD

**Issue by mikeytdisco** [microsoft/mu_feature_dfci#77]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

The DfciPkg\UnitTests\DfciTest testcases all run a command on the device under test to obtain the device manufacturer, product name, and serial number and build packets with this identifying information.  It was not clear at the time the tests were made which serial number to use, as all of the devices being tested had the same serial number for the Type1 and Type3 SMBIOS Serial number.  That is, until a recent OEM had a laptop with different serial numbers for the Type1 and Type3 tables.

### Expected Behavior

The test cases should use the Type1 serial number.

### Steps To Reproduce

Run the Dfci_IntuneEnroll testcase with a system that has
1. Different serial numbers for the Type1 and Type3 BIOS tables
2. Has a properly fixed DfciDeviceIdSupportLib platform library that sets the DeviceId to the Type1 serial number
3. Fixes the Robot script to obtain the Type1 serial number for building the packets

### Build Environment

```markdown
- OS(s):
- Tool Chain(s):
- Targets Impacted:
```

### Version Information

```text
Tag V2.0.1
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
Assigning to @Flickdm to move the PR to closure
